#!/usr/bin/env python3
"""
LLMemoryMeter CLI Entry Point
"""

import sys
import os

# Add the package to Python path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '.'))

from llmemory_meter.cli import main

if __name__ == '__main__':
    main()
